FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1

COPY pyproject.toml uv.lock README.md ./

RUN uv sync --no-dev --frozen

COPY . .

COPY data /data
ENV DATA_DIR=/data

EXPOSE 8080

ENV PATH="/app/.venv/bin:$PATH"

CMD ["uvicorn", "app.mcp_server:create_mcp_app", "--factory", "--host", "0.0.0.0", "--port", "8080"]
